[HOST_SYSTEM]

# Define computer centre.
COMPCENTRE="LOCAL"

# Define hosts
HOSTS = ["ppi-bionic", "ppi-centos7"]

# Location of working data, fast and large system
# Experiment identifier and directories
# EXP is defined when an experiment is started by "Harmonie start ..."
SFX_EXP_DATA = "/lustre/storeB/users/@USER@/sfx_data/@EXP@"
# directory for scripts, compiled objects, executables
SFX_EXP_LIB = "/lustre/storeB/users/@USER@/sfx_data/@EXP@/lib@STREAM@"
JOBOUTDIR = "/lustre/storeB/users/@USER@/sfx_data/@EXP@/job"
LOGIN_HOST = "ppi-blogin-a1.met.no"
HM_CS = "gfortran"
PARCH = ""
MKDIR = "mkdir -p"
RSYNC = "rsync  -rltoDvh"
SCHEDULER_PYTHONPATH = "/modules/bionic/user-apps/suv/pysurfex-scheduler/0.0.1-dev/:/modules/bionic/user-apps/ecflow/5.5.2-ssl/lib/python3.6/site-packages"
SURFEX_CONFIG = "ppi_centos7"

[HOST_SYSTEM.HOST1]
SCHEDULER_PYTHONPATH = "/modules/centos7/user-apps/suv/pysurfex-scheduler/0.0.1-dev/:/modules/centos7/user-apps/ecflow/5.3.0/lib/python3.7/site-packages"
LOGIN_HOST = "ppi-clogin-a1.met.no"
SYNC_DATA = false
