# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd ${GITHUB_WORKSPACE}
        sudo apt-get update && sudo apt-get install -y \
        curl python3 python3-pip libeccodes-dev \
        libproj-dev libudunits2-dev python3-sphinx

        curl -sSL https://install.python-poetry.org | python3 -
        python3 -m pip install setuptools --upgrade
        ~/.local/bin/poetry install

    - name: Unit testing and coverage
      run: |
        ~/.local/bin/poetry run python --version
        ~/.local/bin/poetry run coverage run -m unittest discover
        ~/.local/bin/poetry run coverage html
        ~/.local/bin/poetry run coverage xml
        
    - name: Coveralls
      if: ${{ matrix.python-version == 3.8 }}
      run: |
        cd ${GITHUB_WORKSPACE}
        python3 -m pip install coveralls
        export COVERALLS_REPO_TOKEN=${{secrets.COVERALLS_REPO_TOKEN}}
        coveralls
    - name: Create documentation
      if: ${{ matrix.python-version == 3.8 }}
      run: |
        cd docs
        ./build.sh
    - name: Commit documentation changes
      if: ${{ matrix.python-version == 3.8 }}
      run: |
        git clone https://github.com/metno/pysurfex-experiment.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      if: ${{ matrix.python-version == 3.8 }}
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
